words = [
    "APPLE", "BANANA", "COMPUTER", "ELEPHANT", "GUITAR", "HAPPINESS", "INTERNET", "JUNGLE", "KANGAROO", "LEMON",
    "MOUNTAIN", "NOTEBOOK", "OCTOPUS", "PENGUIN", "QUILT", "RAINBOW", "SUNSHINE", "TELESCOPE", "UMBRELLA", "VACATION",
    "WATERFALL", "XYLOPHONE", "YOGA", "ZEBRA", "ASTRONAUT", "BUTTERFLY", "CHOCOLATE", "DOLPHIN", "ELEPHANT", "FIREWORKS",
    "GALAXY", "HELICOPTER", "ISLAND", "JELLYFISH", "KOALA", "LIGHTNING", "MOONLIGHT", "NARWHAL", "OCEAN", "PENGUIN",
    "QUANTUM", "RAINBOW", "STARFISH", "THUNDER", "UNIVERSE", "VOLCANO", "WATERMELON", "XENON", "YAK", "ZEPPELIN",
    "ADVENTURE", "BALLOON", "CACTUS", "DRAGON", "ELEPHANT", "FOUNTAIN", "GALAXY", "HONEY", "ICE CREAM", "JUNGLE",
    "KITE", "LIGHTHOUSE", "MUSHROOM", "NARWHAL", "OASIS", "PINEAPPLE", "QUOKKA", "RAINFOREST", "SEAHORSE", "TELESCOPE",
    "UMBRELLA", "VOLCANO", "WATERFALL", "XYLOPHONE", "YOGURT", "ZUCCHINI", "BUMBLEBEE", "CAROUSEL", "DINOSAUR",
    "ESPRESSO", "FLAMINGO", "GUITAR", "HOT AIR BALLOON", "IGUANA", "JIGSAW", "KALEIDOSCOPE", "LIGHTHOUSE", "MOONBEAM",
    "NARWHAL", "OSTRICH", "PENCIL", "QUILT", "RAINBOW", "SEAHORSE", "THUNDERSTORM", "UNIVERSE", "VIOLIN", "WATERMELON",
    "XYLOPHONE", "YOGURT"
]
